name = "JOLI4Flux"
uuid = "c228d1c8-a1cf-11e9-3cb4-9bd0a4cd14fc"
authors = ["Henryk Modzelewski <henryk_modzelewski@mac.com>"]
version = "0.1.2"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
JOLI = "bb331ad6-a1cf-11e9-23da-9bcb53c69f6f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = ">= 0.7"
